import { Article } from '~/types/models';
import {
  BLUE,
  BROWN,
  CLOUD,
  GRAY,
  GREEN,
  ORANGE,
  PURPLE,
  RED,
  YELLOW,
} from './colors';

export const ARTICLES: Article[] = [
  {
    id: '1',
    title: 'Продукты',
    nameIcon: 'shopping-cart',
    color: GREEN,
    articleType: 'Expenses',
  },
  {
    id: '2',
    title: 'Кредит',
    nameIcon: 'credit-card',
    color: RED,
    articleType: 'Expenses',
  },
  {
    id: '3',
    title: 'Жилье',
    nameIcon: 'home',
    color: BLUE,
    articleType: 'Expenses',
  },
  {
    id: '4',
    title: 'Здоровье',
    nameIcon: 'thermometer',
    color: YELLOW,
    articleType: 'Expenses',
  },
  {
    id: '5',
    title: 'Кафе',
    nameIcon: 'coffee',
    color: ORANGE,
    articleType: 'Expenses',
  },
  {
    id: '6',
    title: 'Машина',
    nameIcon: 'automobile',
    color: PURPLE,
    articleType: 'Expenses',
  },
  {
    id: '7',
    title: 'Такси',
    nameIcon: 'taxi',
    color: BROWN,
    articleType: 'Expenses',
  },
  {
    id: '8',
    title: 'Одежда',
    nameIcon: 'shopping-bag',
    color: GRAY,
    articleType: 'Expenses',
  },
  {
    id: '9',
    title: 'Питомцы',
    nameIcon: 'paw',
    color: CLOUD,
    articleType: 'Expenses',
  },
  {
    id: '10',
    title: 'Подарки',
    nameIcon: 'gift',
    color: GREEN,
    articleType: 'Expenses',
  },
  {
    id: '11',
    title: 'Развлечения',
    nameIcon: 'gamepad',
    color: RED,
    articleType: 'Expenses',
  },
  {
    id: '12',
    title: 'Связь',
    nameIcon: 'mobile',
    color: BLUE,
    articleType: 'Expenses',
  },
  {
    id: '13',
    title: 'Спорт',
    nameIcon: 'futbol-o',
    color: YELLOW,
    articleType: 'Expenses',
  },
  {
    id: '14',
    title: 'Транспорт',
    nameIcon: 'subway',
    color: ORANGE,
    articleType: 'Expenses',
  },
  {
    id: '15',
    title: 'Гигиена',
    nameIcon: 'shower',
    color: PURPLE,
    articleType: 'Expenses',
  },
  {
    id: '16',
    title: 'Сбережения',
    nameIcon: 'calendar-check-o',
    color: BROWN,
    articleType: 'Incomes',
  },
  {
    id: '17',
    title: 'Подарки',
    nameIcon: 'gift',
    color: GRAY,
    articleType: 'Incomes',
  },
  {
    id: '18',
    title: 'Зарплата',
    nameIcon: 'credit-card-alt',
    color: ORANGE,
    articleType: 'Incomes',
  },
  {
    id: '19',
    title: 'Инвестиции',
    nameIcon: 'institution',
    color: PURPLE,
    articleType: 'Incomes',
  },
];
